---

- name: install packages for ansible support
  raw: dnf -y -e0 -d0 install python python-dnf

- name: dnf_install | install rpms
  dnf: name={{ item }} state=latest disable_gpg_check=yes
  with_items: "{{ fed_pkgs }}"
  when: fed_pkgs is defined and fed_pkgs|length > 0

- name: upgrade all packages to latest
  dnf: name=* state=latest disable_gpg_check=yes

- name: install virtualization group
  dnf: name="@Virtualization" state=present disable_gpg_check=yes
