---

- include: ../handlers/restart_services.yml

- name: check cpuinfo for vmx or svm
  command: grep -iE 'vmx|svm' /proc/cpuinfo

- name: copy vagrant-libvirt-rules
  shell: cp /opt/rh/sclo-vagrant1/root/usr/share/vagrant/gems/doc/vagrant-libvirt-*/polkit/10-vagrant-libvirt.rules
    /etc/polkit-1/rules.d
  notify:
    - restart libvirtd
    - restart polkit

- name: create cdk user and add it to vagrant group
  user: name=cdk shell=/bin/bash groups=vagrant append=yes